name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: $GCP_WORKLOAD_IDENTITY_PROVIDER
        service_account: $GCP_SERVICE_ACCOUNT

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: freeroutingv2
        image: gcr.io/firstcloudrun-323509/freeroutingv2
        region: asia-northeast1

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
